version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: playlist-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    container_name: playlist-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=new_password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"